2023-07-15 20:22:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "imagen" ya existe
Table "imagen" already exists; SQL statement:
CREATE TABLE IMAGEN (NOMBRE VARCHAR  NOT NULL, ARCHIVO BYTEA, TIPO VARCHAR, PRIMARY KEY(NOMBRE)) [42101-220]
2023-07-24 18:52:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "imagen" ya existe
Table "imagen" already exists; SQL statement:
CREATE TABLE IMAGEN (NOMBRE VARCHAR  NOT NULL, ARCHIVO BYTEA, TIPO VARCHAR, PRIMARY KEY(NOMBRE)) [42101-220]
2023-08-25 20:32:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "imagen" ya existe
Table "imagen" already exists; SQL statement:
CREATE TABLE IMAGEN (NOMBRE VARCHAR  NOT NULL, ARCHIVO BYTEA, TIPO VARCHAR, PRIMARY KEY(NOMBRE)) [42101-220]
2023-08-26 21:25:57 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "imagen" ya existe
Table "imagen" already exists; SQL statement:
CREATE TABLE IMAGEN (NOMBRE VARCHAR  NOT NULL, ARCHIVO BYTEA, TIPO VARCHAR, PRIMARY KEY(NOMBRE)) [42101-220]
2023-08-26 21:36:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "imagen" ya existe
Table "imagen" already exists; SQL statement:
CREATE TABLE IMAGEN (NOMBRE VARCHAR  NOT NULL, ARCHIVO BYTEA, TIPO VARCHAR, PRIMARY KEY(NOMBRE)) [42101-220]
2023-08-26 21:43:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "imagen" ya existe
Table "imagen" already exists; SQL statement:
CREATE TABLE IMAGEN (NOMBRE VARCHAR  NOT NULL, ARCHIVO BYTEA, TIPO VARCHAR, PRIMARY KEY(NOMBRE)) [42101-220]
2023-08-27 03:34:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "imagen" ya existe
Table "imagen" already exists; SQL statement:
CREATE TABLE IMAGEN (NOMBRE VARCHAR  NOT NULL, ARCHIVO BYTEA, TIPO VARCHAR, PRIMARY KEY(NOMBRE)) [42101-220]
2023-08-27 03:35:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "imagen" ya existe
Table "imagen" already exists; SQL statement:
CREATE TABLE IMAGEN (NOMBRE VARCHAR  NOT NULL, ARCHIVO BYTEA, TIPO VARCHAR, PRIMARY KEY(NOMBRE)) [42101-220]
2023-08-27 03:41:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "imagen" ya existe
Table "imagen" already exists; SQL statement:
CREATE TABLE IMAGEN (NOMBRE VARCHAR  NOT NULL, ARCHIVO BYTEA, TIPO VARCHAR, PRIMARY KEY(NOMBRE)) [42101-220]
2023-08-27 03:50:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "imagen" ya existe
Table "imagen" already exists; SQL statement:
CREATE TABLE IMAGEN (NOMBRE VARCHAR  NOT NULL, ARCHIVO BYTEA, TIPO VARCHAR, PRIMARY KEY(NOMBRE)) [42101-220]
2023-08-27 03:58:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "imagen" ya existe
Table "imagen" already exists; SQL statement:
CREATE TABLE IMAGEN (NOMBRE VARCHAR  NOT NULL, ARCHIVO BYTEA, TIPO VARCHAR, PRIMARY KEY(NOMBRE)) [42101-220]
2023-08-27 03:59:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "imagen" ya existe
Table "imagen" already exists; SQL statement:
CREATE TABLE IMAGEN (NOMBRE VARCHAR  NOT NULL, ARCHIVO BYTEA, TIPO VARCHAR, PRIMARY KEY(NOMBRE)) [42101-220]
2023-08-27 04:01:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "imagen" ya existe
Table "imagen" already exists; SQL statement:
CREATE TABLE IMAGEN (NOMBRE VARCHAR  NOT NULL, ARCHIVO BYTEA, TIPO VARCHAR, PRIMARY KEY(NOMBRE)) [42101-220]
2023-08-27 04:07:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "imagen" ya existe
Table "imagen" already exists; SQL statement:
CREATE TABLE IMAGEN (NOMBRE VARCHAR  NOT NULL, ARCHIVO BYTEA, TIPO VARCHAR, PRIMARY KEY(NOMBRE)) [42101-220]
2023-08-27 09:23:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "imagen" ya existe
Table "imagen" already exists; SQL statement:
CREATE TABLE IMAGEN (NOMBRE VARCHAR  NOT NULL, ARCHIVO BYTEA, TIPO VARCHAR, PRIMARY KEY(NOMBRE)) [42101-220]
2023-08-27 09:40:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "imagen" ya existe
Table "imagen" already exists; SQL statement:
CREATE TABLE IMAGEN (NOMBRE VARCHAR  NOT NULL, ARCHIVO BYTEA, TIPO VARCHAR, PRIMARY KEY(NOMBRE)) [42101-220]
2023-08-27 09:41:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "imagen" ya existe
Table "imagen" already exists; SQL statement:
CREATE TABLE IMAGEN (NOMBRE VARCHAR  NOT NULL, ARCHIVO BYTEA, TIPO VARCHAR, PRIMARY KEY(NOMBRE)) [42101-220]
2023-08-27 09:41:42 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "imagen" ya existe
Table "imagen" already exists; SQL statement:
CREATE TABLE IMAGEN (NOMBRE VARCHAR  NOT NULL, ARCHIVO BYTEA, TIPO VARCHAR, PRIMARY KEY(NOMBRE)) [42101-220]
2023-08-27 10:28:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Columna "nombre.archivo" no encontrada
Column "nombre.archivo" not found; SQL statement:
SELECT nombre,
	archivo
FROM imagen
WHERE 
	 nombre.archivo =  ? [42122-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:244)
	at org.h2.expression.ExpressionColumn.optimizeOther(ExpressionColumn.java:226)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:213)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:147)
	at org.h2.expression.Expression.optimizeCondition(Expression.java:148)
	at org.h2.command.query.Select.prepareExpressions(Select.java:1177)
	at org.h2.command.query.Query.prepare(Query.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:583)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:634)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:557)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at net.sf.jasperreports.engine.query.JRJdbcQueryExecuter.createStatement(JRJdbcQueryExecuter.java:404)
	at net.sf.jasperreports.engine.query.JRJdbcQueryExecuter.createDatasource(JRJdbcQueryExecuter.java:299)
	at net.sf.jasperreports.engine.fill.JRFillDataset.createQueryDatasource(JRFillDataset.java:1286)
	at net.sf.jasperreports.engine.fill.JRFillDataset.initDatasource(JRFillDataset.java:736)
	at net.sf.jasperreports.engine.fill.BaseReportFiller.setParameters(BaseReportFiller.java:458)
	at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:591)
	at net.sf.jasperreports.engine.fill.BaseFillHandle$ReportFill.run(BaseFillHandle.java:135)
	at java.base/java.lang.Thread.run(Thread.java:1623)
2023-08-27 10:30:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "imagen" ya existe
Table "imagen" already exists; SQL statement:
CREATE TABLE IMAGEN (NOMBRE VARCHAR  NOT NULL, ARCHIVO BYTEA, TIPO VARCHAR, PRIMARY KEY(NOMBRE)) [42101-220]
2023-09-06 21:37:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "imagen" ya existe
Table "imagen" already exists; SQL statement:
CREATE TABLE IMAGEN (NOMBRE VARCHAR  NOT NULL, ARCHIVO BYTEA, TIPO VARCHAR, PRIMARY KEY(NOMBRE)) [42101-220]
2023-09-17 14:19:32.366115-04:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "imagen" ya existe
Table "imagen" already exists; SQL statement:
CREATE TABLE IMAGEN (NOMBRE VARCHAR  NOT NULL, ARCHIVO BYTEA, TIPO VARCHAR, PRIMARY KEY(NOMBRE)) [42101-224]
2024-06-18 20:19:43.025771-04:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "imagen" ya existe
Table "imagen" already exists; SQL statement:
CREATE TABLE IMAGEN (NOMBRE VARCHAR  NOT NULL, ARCHIVO BYTEA, TIPO VARCHAR, PRIMARY KEY(NOMBRE)) [42101-224]
2024-06-18 20:22:55.027675-04:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Deserialización fallida, causa: "java.io.StreamCorruptedException: invalid stream header: FFD8FFE0"
Deserialization failed, cause: "java.io.StreamCorruptedException: invalid stream header: FFD8FFE0" [90027-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.util.JdbcUtils.deserialize(JdbcUtils.java:432)
	at org.h2.value.ValueToObjectConverter.valueToOther(ValueToObjectConverter.java:356)
	at org.h2.value.ValueToObjectConverter.valueToObject(ValueToObjectConverter.java:339)
	at org.h2.jdbc.JdbcResultSet.getObject(JdbcResultSet.java:4196)
	at net.sf.jasperreports.engine.JRResultSetDataSource.getFieldValue(JRResultSetDataSource.java:401)
	at net.sf.jasperreports.engine.fill.JRFillDataset.setOldValues(JRFillDataset.java:1533)
	at net.sf.jasperreports.engine.fill.JRFillDataset.next(JRFillDataset.java:1434)
	at net.sf.jasperreports.engine.fill.JRFillDataset.next(JRFillDataset.java:1410)
	at net.sf.jasperreports.engine.fill.JRBaseFiller.next(JRBaseFiller.java:1210)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReport(JRVerticalFiller.java:117)
	at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:631)
	at net.sf.jasperreports.engine.fill.BaseFillHandle$ReportFill.run(BaseFillHandle.java:135)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.io.StreamCorruptedException: invalid stream header: FFD8FFE0
	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:974)
	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:401)
	at org.h2.util.JdbcUtils.deserialize(JdbcUtils.java:428)
	... 12 more
2024-06-18 20:24:35.421061-04:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Deserialización fallida, causa: "java.io.StreamCorruptedException: invalid stream header: FFD8FFE0"
Deserialization failed, cause: "java.io.StreamCorruptedException: invalid stream header: FFD8FFE0" [90027-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.util.JdbcUtils.deserialize(JdbcUtils.java:432)
	at org.h2.value.ValueToObjectConverter.valueToOther(ValueToObjectConverter.java:356)
	at org.h2.value.ValueToObjectConverter.valueToObject(ValueToObjectConverter.java:339)
	at org.h2.jdbc.JdbcResultSet.getObject(JdbcResultSet.java:4196)
	at net.sf.jasperreports.engine.JRResultSetDataSource.getFieldValue(JRResultSetDataSource.java:401)
	at net.sf.jasperreports.engine.fill.JRFillDataset.setOldValues(JRFillDataset.java:1533)
	at net.sf.jasperreports.engine.fill.JRFillDataset.next(JRFillDataset.java:1434)
	at net.sf.jasperreports.engine.fill.JRFillDataset.next(JRFillDataset.java:1410)
	at net.sf.jasperreports.engine.fill.JRBaseFiller.next(JRBaseFiller.java:1210)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReport(JRVerticalFiller.java:117)
	at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:631)
	at net.sf.jasperreports.engine.fill.BaseFillHandle$ReportFill.run(BaseFillHandle.java:135)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.io.StreamCorruptedException: invalid stream header: FFD8FFE0
	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:974)
	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:401)
	at org.h2.util.JdbcUtils.deserialize(JdbcUtils.java:428)
	... 12 more
2024-06-18 20:24:39.738490-04:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Deserialización fallida, causa: "java.io.StreamCorruptedException: invalid stream header: FFD8FFE0"
Deserialization failed, cause: "java.io.StreamCorruptedException: invalid stream header: FFD8FFE0" [90027-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.util.JdbcUtils.deserialize(JdbcUtils.java:432)
	at org.h2.value.ValueToObjectConverter.valueToOther(ValueToObjectConverter.java:356)
	at org.h2.value.ValueToObjectConverter.valueToObject(ValueToObjectConverter.java:339)
	at org.h2.jdbc.JdbcResultSet.getObject(JdbcResultSet.java:4196)
	at net.sf.jasperreports.engine.JRResultSetDataSource.getFieldValue(JRResultSetDataSource.java:401)
	at net.sf.jasperreports.engine.fill.JRFillDataset.setOldValues(JRFillDataset.java:1533)
	at net.sf.jasperreports.engine.fill.JRFillDataset.next(JRFillDataset.java:1434)
	at net.sf.jasperreports.engine.fill.JRFillDataset.next(JRFillDataset.java:1410)
	at net.sf.jasperreports.engine.fill.JRBaseFiller.next(JRBaseFiller.java:1210)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReport(JRVerticalFiller.java:117)
	at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:631)
	at net.sf.jasperreports.engine.fill.BaseFillHandle$ReportFill.run(BaseFillHandle.java:135)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.io.StreamCorruptedException: invalid stream header: FFD8FFE0
	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:974)
	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:401)
	at org.h2.util.JdbcUtils.deserialize(JdbcUtils.java:428)
	... 12 more
